### ISSUE TITLE
Linux [Ubuntu 20.04 LTS] Error: Failed to load module “canberra-gtk-module"

### ISSUE THREAD

**Issue by simbleau** [qarmin/szyszka#11]
When starting the application, stdout alarms:
`Failed to load module “canberra-gtk-module”`

I fixed this through installing the dependency 
`sudo apt-get install libcanberra-gtk-module`

And restarted bash with a PATH export like such:
`LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/gtk-3.0/modules:$LD_LIBRARY_PATH ./szyszka`

**Comment by MGlolenstine** [comment]
I'm pretty sure that the issue has been closed with #12 (as it's named that way).

Hint: If you prepend issue number using `Fixes #<number>` or `Closes #<number>` the issue will automatically close when the PR is merged.

**Comment by simbleau** [comment]
Yup this is done.
