### ISSUE TITLE
Typo in readme.

### ISSUE THREAD

**Issue by hishamduke** [qarmin/szyszka#18]
Some minor typos in Readme.md

**Comment by MGlolenstine** [comment]
I think that these should be mostly fixed with #10 and #16 .
If there are any left, please let me know!

**Comment by hishamduke** [comment]
Change coulnd't to couldn't in the Why section of readme.
Sorry for bothering you im new to GitHub and development. Thankyou for your work btw !

**Comment by MGlolenstine** [comment]
Thank you, that was one I missed!
I think #25 should fix this typo.
