### ISSUE TITLE
Feature Request: Select 'not in tree'

### ISSUE THREAD

**Issue by rorytm** [qarmin/szyszka#21]
Thanks for the program, it looks great! Sadly, my random use case that popped up right after I saw it isn't covered.

I'd like to be able to compare duplicates as is, but then, on the selection, have the option to select (and delete) all of the files that are  in a selected directory tree. I have multiple copies of the same folder that have diverged and I essentially want to keep one tree as is, and then only keep the files that are different in the second tree.

**Comment by qarmin** [comment]
This is probably issue with Czkawka, not a Szyszka, but feel free to reopen this
