### ISSUE TITLE
Unable to add files from external drives

### ISSUE THREAD

**Issue by agentsars** [qarmin/szyszka#30]
When trying to add files from an external drive it gives me the following error:
`Unable to get creation date from file X`

Happens when running as root and not. Happens when using appimage as well as compiled from source.
OS: Artix (linux 5.12.12.artix1-1)

**Comment by qarmin** [comment]
Some filesystems(or its Linux drivers) doesn't provide information's about creation date.
I tested several file systems and find that at least in Ubuntu 21.10, NTFS and FAT doesn't provide such info.
I couldn't find any wrong behavior in app
In #60 I added native error explanation which will help user to find exact issue why such error happens
