### ISSUE TITLE
Add icons to snap

### ISSUE THREAD

**Issue by qarmin** [qarmin/szyszka#38]
Don't work for now

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> BEEDELLROKEJULIANLOCKHART@localhost:~> snap run szyszka
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Gtk-Message: 08:03:52.817: Failed to load module "colorreload-gtk-module"
Gtk-Message: 08:03:52.817: Failed to load module "window-decorations-gtk-module"

**Comment by qarmin** [comment]
This should be fixed by https://github.com/qarmin/szyszka/commit/87f711321b86aaac139670775733d5df85ceb975 
With flatpak it will be harder to fix this, because I don't have idea how to fix this.
