### ISSUE TITLE
Cannot input the colon (:) when editing the custom renaming rules

### ISSUE THREAD

**Issue by erbanku** [qarmin/szyszka#40]
Cannot input the colon (:) when editing the custom renaming rules.

**As below:**

![ShareX_2021-07-20_13-37-41](https://user-images.githubusercontent.com/79493862/126268097-b3c1dec6-fcdf-4f0f-9273-27fc65488aa7.gif)

**Comment by qarmin** [comment]
Hmm... 
I disabled colon because windows names cannot contains them, but I that this solution is not correct.

**Comment by erbanku** [comment]
I think the solution maybe:
Can contain a colon when editing a renaming rule, but doesn't contain colon when finally modify the file name.

**Comment by qarmin** [comment]
Fixed by 0fe9753eceac56321a49b44c6ec390d30ba0a494
