### ISSUE TITLE
Feature request - Simple CLI access for specifying files

### ISSUE THREAD

**Issue by celynw** [qarmin/szyszka#41]
I'd love to be able to use this as a rename utility from a file browser such as [nemo](https://github.com/linuxmint/nemo).
In nemo in particular, you can select multiple files to rename, then press `F2` and then the list is populated with those files/folders.

It requires something like this command:
```
szyszka %F
```
where `%F` would be a list of N items.

Some examples of other rename utilities which work like this are `thunar --bulk-rename`, `krename` and `gprename`.

I'm not asking for a full CLI interface as I see there currently isn't one.
Instead I was hoping this would be relatively simple to implement.

Thanks!

**Comment by tkapias** [comment]
I'd like to use it from thunar custom actions, we need that feature.

Thanks!
