### ISSUE TITLE
libatk wrong version?

### ISSUE THREAD

**Issue by macmeister1967** [qarmin/szyszka#43]
Reason: Incompatible library version: mac_szyszka requires version 23610.0.0 or later, but libatk-1.0.0.dylib provides version 23010.0.0

Abort trap: 6

I installed Rust & GTK+3 via homebrew as recommended,  but this old version still seems to be taking precedence...

Any idea what I can do now?

**Comment by qarmin** [comment]
In CI, the latest homebrew version of gtk is used without any tricks etc. 
https://github.com/qarmin/szyszka/blob/827b94496f09f0d0bea14e0d2f44bdf0496b1f76/.github/workflows/mac.yml#L28-L29

basing on this site https://formulae.brew.sh/formula/atk#default, the latest version of libatk is `2.36` which I think is shown sometimes as `23610.0.0`

I never used homebrew, but I think that you downloaded not the latest version of atk even if newest was available.
I suggest to update homebrew and packages, probably this command is used for this `homebrew update` and `homebrew upgrade`

**Comment by qarmin** [comment]
Gtk 4.6 with updated atk dependency is now required
