### ISSUE TITLE
Exchanging file names for numbering reverses order of files

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [qarmin/szyszka#51]
I would like to use this program to replace the name of files by a sequence of numbers to shorten the file name. Now there is the issue, that the order of the files will be inverted by default and I have to reorder the files by hand. This is feasible for a small number of files, but not if the mount of files goes into the hundreds or thousands. Is there an option to fix this, like ordering the files ascending instead of descending by clicking "current name" in the header?

![Bildschirmfoto von 2021-08-11 21-02-49](https://user-images.githubusercontent.com/41188546/129088517-2371287e-14be-4723-a81b-f4e89bb04128.png)

**Comment by qarmin** [comment]
When checking recursively folders, output was even more random.
This will be fixed by #57
