### ISSUE TITLE
The Flatpak package of szyszka is not able to load canberra-gtk-module, and thus, custom iconography.

### ISSUE THREAD

**Issue by rokejulianlockhart** [qarmin/szyszka#54]
The [`flatpak`](http://flatpak.org) package that is available at "http://dl.flathub.org/repo/appstream/com.github.qarmin.szyszka" is unable to load the [`canberra-gtk-module`](http://wikipedia.org/wiki/Libcanberra), which is demonstrated by [this log](http://github.com/qarmin/szyszka/files/7026079/20210821T142113Z.DAT.BIN.TXT.LOG).

![This depicts the problem.](https://user-images.githubusercontent.com/42837531/130322757-254f9a0f-ac9e-4f18-a062-22bb52e30216.png)

The [`snap`](http://snapcraft.io/)-package that is available at "http://snapcraft.io/szyszka" is additionally unable to load the [`canberra-gtk-module`](http://wikipedia.org/wiki/Libcanberra), which is demonstrated by the output that is available at "https://github.com/qarmin/szyszka/issues/38#issuecomment-903112786".

**Comment by qarmin** [comment]
App now have builtin icons, will be available in new version of Flatpak(I need only provide dark themed icons )

**Comment by rokejulianlockhart** [comment]
@qarmin, does that mean that it doesn't use native icons anymore? :<

**Comment by qarmin** [comment]
Yes, but now also there are only 4 icons - up, down, settings, reset example.
Each distro/OS/theme used different set of icons, so there was no way that, using the same set of built-in icons, would look good everywhere
