### ISSUE TITLE
Segmentation on Debian 10

### ISSUE THREAD

**Issue by canonex** [qarmin/szyszka#64]
On debian 10 + Gnome, using the AppImage (release 2.0.0) i get, as soon as I click "Add Folders":

```
$ ./linux_szyszka.AppImage 
Gtk-Message: 20:33:04.767: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:33:04.768: Failed to load module "canberra-gtk-module"
/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
Errore di segmentazione
```

libgioremote-volume-monitor.so is not available.

More, package libgtk3-dev
```
apt install libgtk3-dev
...
E: Cannot find package libgtk3-dev
```
I tried installing libgtk3.0-cil-dev but I don't know if is really the same...

Flatpack and Snap versions are working fine.

Thank you,
Riccardo

**Comment by qarmin** [comment]
On debian, gtk3 package is probably named - `libgtk-3-dev`.
There is segmentation fault, so probably gdb should show more info about it(looks that there is a problem with C/C++ code(maybe caused by GTK), Rust usually panic with more detailed backtrace)

**Comment by canonex** [comment]
I checked libgtk-3-dev, it is already installed at version 3.24.5-1...

**Comment by qarmin** [comment]
New version use GTK 4.6
